<?php

namespace PaLogic\Bundle\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetCategoryRepository extends EntityRepository
{
    public function getSetCategories() {
        return $this->createQueryBuilder('c')
            ->leftJoin('c.sets','s')
            ->orderBy('s.orderNumber', 'asc')
            ->getQuery()
            ->getResult();
    }

    public function findSetCategoryById($id) {
        return $this->createQueryBuilder('c')
            ->where('c.id = ?1')
            ->leftJoin('c.sets','s')
            ->orderBy('s.orderNumber', 'asc')
            ->setParameter(1, $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
