<?php

namespace PaLogic\Bundle\DjBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DjRepository extends EntityRepository
{
    public static function filterOutEmptyGenres(array $genres) {
        /*
         * filter out genres without approved dj's
         */
        $filteredGenres = array();
        /* @var \PaLogic\Bundle\DjBundle\Entity\Genre $genre  */
        foreach ($genres as $genre) {
            $containsEnabledDj = false;
            /* @var \PaLogic\Bundle\DjBundle\Entity\Dj $dj */
            foreach ($genre->getDjs() as $dj) {
                if ($dj->getApproved()) {
                    $containsEnabledDj = true;
                }
            }
            if ($containsEnabledDj) {
                $filteredGenres[] = $genre;
            }
        }
        return $filteredGenres;
    }
}
