<?php

namespace PaLogic\Bundle\DjBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DjRepository extends EntityRepository
{
}
